import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  {
    title: 'Notebook Acer Aspire 5 Intel Core i5 16GB SSD 512GB',
    category: 'Notebooks',
    price: 'R$ 2.999,00',
    oldPrice: 'R$ 3.529,00',
    discount: '-15%',
    image: '/produtos/Notebook-Acer-Aspire-5.jpg',
    rating: 150,
    store: 'Mercado Livre',
    installments: '10x de R$ 299,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1xjmjVS',
  },
  {
    title: 'Impressora multifuncional cor Epson EcoTank L3250',
    category: 'Impressora',
    price: 'R$ 1.221,00',
    oldPrice: 'R$ 1.359,00',
    discount: '-10%',
    image: '/produtos/Impressora-multifuncional-Epson-L3250.jpg',
    rating: 65000,
    store: 'Mercado livre',
    installments: '12x de 10x R$ 118,53',
    shipping: 'Frete Gratis',
    affiliate: 'https://meli.la/286F1hT',
  },
  {
    title: 'Notebook Lenovo IdeaPad 1 Ryzen 5 7520U 8GB SSD 256GB',
    category: 'Notebooks',
    price: 'R$ 2.399,00',
    oldPrice: 'R$ 2.799,00',
    discount: '-14%',
    image: '/produtos/Notebook-Lenovo-IdeaPad-1.webp',
    rating: 420,
    store: 'Mercado Livre',
    installments: '10x de R$ 239,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1SKAReQ',
  },
  {
    title: 'Notebook Dell Inspiron 15 Core i5 16GB SSD 512GB',
    category: 'Notebooks',
    price: 'R$ 3.799,00',
    oldPrice: 'R$ 4.299,00',
    discount: '-12%',
    image: '/produtos/Notebook-Dell-Inspiron-15.webp',
    rating: 286,
    store: 'Mercado Livre',
    installments: '10x de R$ 379,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2Vyvqpc',
  },
  {
    title: 'Monitor Gamer LG UltraGear 24 polegadas IPS 180Hz',
    category: 'Monitores',
    price: 'R$ 899,00',
    oldPrice: 'R$ 1.049,00',
    discount: '-14%',
    image: '/produtos/Monitor-LG-UltraGear-24.webp',
    rating: 534,
    store: 'Mercado Livre',
    installments: '10x de R$ 89,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2gMx1SN',
  },
  {
    title: 'Monitor Samsung T350 24 polegadas Full HD IPS',
    category: 'Monitores',
    price: 'R$ 649,00',
    oldPrice: 'R$ 749,00',
    discount: '-13%',
    image: '/produtos/Monitor-Samsung-T350-24.webp',
    rating: 812,
    store: 'Mercado Livre',
    installments: '10x de R$ 64,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2omqkPs',
  },
  {
    title: 'SSD Kingston NV2 1TB NVMe M.2',
    category: 'Armazenamento',
    price: 'R$ 429,90',
    oldPrice: 'R$ 499,90',
    discount: '-14%',
    image: '/produtos/SSD-Kingston-NV2-1TB.webp',
    rating: 1290,
    store: 'Mercado Livre',
    installments: '10x de R$ 42,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1jbxXEX',
  },
  {
    title: 'SSD Kingston A400 480GB SATA',
    category: 'Armazenamento',
    price: 'R$ 219,90',
    oldPrice: 'R$ 259,90',
    discount: '-15%',
    image: '/produtos/SSD-Kingston-A400-480GB.webp',
    rating: 2380,
    store: 'Mercado Livre',
    installments: '7x de R$ 31,41',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1NheSfj',
  },
  {
    title: 'Memória Kingston Fury Beast 16GB DDR4 3200MHz',
    category: 'Componentes',
    price: 'R$ 279,90',
    oldPrice: 'R$ 329,90',
    discount: '-15%',
    image: '/produtos/Memoria-Kingston-Fury-Beast-16GB.webp',
    rating: 746,
    store: 'Mercado Livre',
    installments: '9x de R$ 31,10',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2Eynffk',
  },
  {
    title: 'Teclado Mecânico Gamer Redragon Kumara K552',
    category: 'Periféricos',
    price: 'R$ 249,90',
    oldPrice: 'R$ 299,90',
    discount: '-17%',
    image: '/produtos/Teclado-Redragon-Kumara-K552.webp',
    rating: 1640,
    store: 'Mercado Livre',
    installments: '8x de R$ 31,24',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2CTAKLL',
  },
  {
    title: 'Mouse Gamer Logitech G203 Lightsync RGB',
    category: 'Periféricos',
    price: 'R$ 129,90',
    oldPrice: 'R$ 159,90',
    discount: '-19%',
    image: '/produtos/Mouse-Logitech-G203.webp',
    rating: 3210,
    store: 'Mercado Livre',
    installments: '4x de R$ 32,48',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2cKanGT',
  },
  {
    title: 'Headset Gamer HyperX Cloud Stinger 2',
    category: 'Periféricos',
    price: 'R$ 299,90',
    oldPrice: 'R$ 349,90',
    discount: '-14%',
    image: '/produtos/Headset-HyperX-Cloud-Stinger-2.webp',
    rating: 688,
    store: 'Mercado Livre',
    installments: '10x de R$ 29,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2FaqZ6E',
  },
  {
    title: 'Webcam Logitech C920 Full HD 1080p',
    category: 'Periféricos',
    price: 'R$ 429,90',
    oldPrice: 'R$ 499,90',
    discount: '-14%',
    image: '/produtos/Webcam-Logitech-C920.webp',
    rating: 925,
    store: 'Mercado Livre',
    installments: '10x de R$ 42,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2KHmnWX',
  },
  {
    title: 'Roteador TP-Link Archer AX12 Wi-Fi 6 Dual Band',
    category: 'Redes',
    price: 'R$ 299,90',
    oldPrice: 'R$ 349,90',
    discount: '-14%',
    image: '/produtos/Roteador-TP-Link-Archer-AX12.webp',
    rating: 472,
    store: 'Mercado Livre',
    installments: '10x de R$ 29,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2c5yGC6',
  },
  {
    title: 'Nobreak Intelbras Attiv 1200VA Bivolt',
    category: 'Energia',
    price: 'R$ 749,00',
    oldPrice: 'R$ 849,00',
    discount: '-12%',
    image: '/produtos/Nobreak-Intelbras-Attiv-1200VA.webp',
    rating: 318,
    store: 'Mercado Livre',
    installments: '10x de R$ 74,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1Wx6JkB',
  },
  {
    title: 'Placa de Vídeo Zotac GeForce RTX 4060 Twin Edge 8GB',
    category: 'Componentes',
    price: 'R$ 2.199,00',
    oldPrice: 'R$ 2.499,00',
    discount: '-12%',
    image: '/produtos/Placa-Video-Zotac-RTX-4060.webp',
    rating: 359,
    store: 'Mercado Livre',
    installments: '10x de R$ 219,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1VgnfYT',
  },
  {
    title: 'Processador AMD Ryzen 5 5600GT com Radeon Graphics',
    category: 'Componentes',
    price: 'R$ 899,00',
    oldPrice: 'R$ 1.049,00',
    discount: '-14%',
    image: '/produtos/Processador-AMD-Ryzen-5-5600GT.webp',
    rating: 587,
    store: 'Mercado Livre',
    installments: '10x de R$ 89,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/29PKCVx',
  },
  {
    title: "Notebook Samsung Galaxy Book4 Intel Core i3 8GB SSD 256GB",
    category: "Notebooks",
    price: "R$ 3.399,15",
    oldPrice: "R$ 3.999,00",
    discount: "-15%",
    image: "/produtos/Notebook-Samsung-Galaxy-Book4.webp",
    rating: 412,
    store: "Mercado Livre",
    installments: "10x de R$ 339,92",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2j8hbRb",
  },
  {
    title: "Notebook ASUS Vivobook Go 15 Ryzen 5 8GB SSD 512GB",
    category: "Notebooks",
    price: "R$ 2.899,00",
    oldPrice: "R$ 3.299,00",
    discount: "-12%",
    image: "/produtos/Notebook-ASUS-Vivobook-Go-15.webp",
    rating: 268,
    store: "Mercado Livre",
    installments: "10x de R$ 289,90",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2JNGaNj",
  },
  {
    title: "Impressora Multifuncional Canon Pixma G3110 Wi-Fi",
    category: "Impressora",
    price: "R$ 849,00",
    oldPrice: "R$ 1.079,00",
    discount: "-21%",
    image: "/produtos/Impressora-Canon-Pixma-G3110.webp",
    rating: 2186,
    store: "Mercado Livre",
    installments: "10x de R$ 84,90",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1iCorvj",
  },
  {
    title: "Impressora Multifuncional HP Smart Tank 581 Wi-Fi",
    category: "Impressora",
    price: "R$ 909,99",
    oldPrice: "R$ 1.901,05",
    discount: "-52%",
    image: "/produtos/Impressora-HP-Smart-Tank-581.webp",
    rating: 13564,
    store: "Mercado Livre",
    installments: "10x de R$ 91,00",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2kLAMiM",
  },
  {
    title: "Impressora Multifuncional Epson EcoTank L4360 Wi-Fi Duplex",
    category: "Impressora",
    price: "R$ 1.499,00",
    oldPrice: "R$ 1.879,00",
    discount: "-20%",
    image: "/produtos/Impressora-Epson-EcoTank-L4360.webp",
    rating: 1843,
    store: "Mercado Livre",
    installments: "10x de R$ 149,90",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2zAetE9",
  },
  {
    title: "Impressora Multifuncional HP Smart Tank 724 Wi-Fi Duplex",
    category: "Impressora",
    price: "R$ 1.304,10",
    oldPrice: "R$ 1.449,00",
    discount: "-10%",
    image: "/produtos/Impressora-HP-Smart-Tank-724.webp",
    rating: 1056,
    store: "Mercado Livre",
    installments: "10x de R$ 130,41",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/24EFC4Q",
  },
  {
    title: "Monitor Gamer AOC Agon 24G50F 24\" 144Hz IPS",
    category: "Monitores",
    price: "R$ 622,00",
    oldPrice: "R$ 1.070,00",
    discount: "-41%",
    image: "/produtos/Monitor-AOC-Agon-24G50F.webp",
    rating: 1000,
    store: "Mercado Livre",
    installments: "12x de R$ 60,15",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/285Wxtv",
  },
  {
    title: "Monitor Gamer LG UltraGear 24G411A-B 24\" 144Hz IPS",
    category: "Monitores",
    price: "R$ 749,00",
    oldPrice: "R$ 799,00",
    discount: "-6%",
    image: "/produtos/Monitor-LG-UltraGear-24G411A.webp",
    rating: 100,
    store: "Mercado Livre",
    installments: "12x de R$ 72,43",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1mocgLp",
  },
  {
    title: "Monitor Gamer Acer Nitro KG240Y 23,8\" 240Hz IPS",
    category: "Monitores",
    price: "R$ 918,20",
    oldPrice: "R$ 1.069,00",
    discount: "-14%",
    image: "/produtos/Monitor-Acer-Nitro-KG240Y.webp",
    rating: 100,
    store: "Mercado Livre",
    installments: "12x de R$ 89,13",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2VeRJaU",
  },
  {
    title: "Pen Drive 32GB USB em Metal Alta Velocidade",
    category: "Armazenamento",
    price: "R$ 39,67",
    oldPrice: "R$ 49,90",
    discount: "-20%",
    image: "/produtos/Pen-Drive-32GB-Metal.webp",
    rating: 10000,
    store: "Mercado Livre",
    installments: "2x de R$ 19,84",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1mKPGzr",
  },
  {
    title: "SSD Ceamere 240GB SATA",
    category: "Armazenamento",
    price: "R$ 272,90",
    oldPrice: "R$ 299,90",
    discount: "-9%",
    image: "/produtos/SSD-Ceamere-240GB-SATA.webp",
    rating: 1000,
    store: "Mercado Livre",
    installments: "12x de R$ 26,70",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/12Aqe5y",
  },
  {
    title: "Case Externo Pholex USB 3.0 para HD e SSD 2,5\"",
    category: "Armazenamento",
    price: "R$ 24,82",
    oldPrice: "R$ 29,90",
    discount: "-16%",
    image: "/produtos/Case-Externo-Pholex-USB-3.webp",
    rating: 50000,
    store: "Mercado Livre",
    installments: "2x de R$ 12,41",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1i8pXwt",
  },
  {
    title: "Fonte MSI MAG 650W 80 Plus Bronze",
    category: "Componentes",
    price: "R$ 318,71",
    oldPrice: "R$ 599,00",
    discount: "-46%",
    image: "/produtos/Fonte-MSI-MAG-650W.webp",
    rating: 5000,
    store: "Mercado Livre",
    installments: "8x de R$ 39,84",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2b4terz",
  },
  {
    title: "Placa-mãe Gigabyte B760M Aorus Elite DDR5",
    category: "Componentes",
    price: "R$ 910,83",
    oldPrice: "R$ 939,00",
    discount: "-3%",
    image: "/produtos/Placa-Mae-Gigabyte-B760M-Aorus.webp",
    rating: 1000,
    store: "Mercado Livre",
    installments: "12x de R$ 88,42",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1tkfraX",
  },
  {
    title: "Mouse Gamer Attack Shark G3 Pro Sem Fio 25000 DPI",
    category: "Periféricos",
    price: "R$ 146,59",
    oldPrice: "R$ 171,11",
    discount: "-14%",
    image: "/produtos/Mouse-Attack-Shark-G3-Pro.webp",
    rating: 1000,
    store: "Mercado Livre",
    installments: "6x de R$ 24,43",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2bJFv4v",
  },
  {
    title: "Repetidor Wi-Fi Davely 1800 Mbps com Ethernet",
    category: "Redes",
    price: "R$ 42,21",
    oldPrice: "R$ 44,90",
    discount: "-5%",
    image: "/produtos/Repetidor-WiFi-Davely-1800.webp",
    rating: 10000,
    store: "Mercado Livre",
    installments: "2x de R$ 21,11",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/178MnNd",
  },
  {
    title: "Cabo de Rede CAT6 10 Metros Gigabit",
    category: "Redes",
    price: "R$ 22,99",
    oldPrice: "R$ 32,90",
    discount: "-30%",
    image: "/produtos/Cabo-Rede-CAT6-10m.webp",
    rating: 50000,
    store: "Mercado Livre",
    installments: "2x de R$ 11,50",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2hBDgAq",
  },
  {
    title: "Roteador Huawei AX1 Dual Band 1200 Mbps Gigabit",
    category: "Redes",
    price: "R$ 186,00",
    oldPrice: "R$ 299,00",
    discount: "-37%",
    image: "/produtos/Roteador-Huawei-AX1.webp",
    rating: 1000,
    store: "Mercado Livre",
    installments: "12x de R$ 18,41",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2q4gttg",
  },
  {
    title: "Kit TP-Link Deco BE22 Wi-Fi 7 Mesh com 3 Unidades",
    category: "Redes",
    price: "R$ 1.299,00",
    oldPrice: "R$ 1.399,00",
    discount: "-7%",
    image: "/produtos/Kit-TPLink-Deco-BE22.webp",
    rating: 500,
    store: "Mercado Livre",
    installments: "15x de R$ 86,66",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1ay1FDM",
  },
  {
    title: "Power Bank Davely 20000mAh Turbo",
    category: "Energia",
    price: "R$ 71,98",
    oldPrice: "R$ 120,00",
    discount: "-40%",
    image: "/produtos/Power-Bank-Davely-20000mAh.webp",
    rating: 10000,
    store: "Mercado Livre",
    installments: "4x de R$ 18,00",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/2CPvqyh",
  },
  {
    title: "Kit 8 Pilhas Recarregáveis com Carregador Bivolt",
    category: "Energia",
    price: "R$ 49,99",
    oldPrice: "R$ 150,00",
    discount: "-66%",
    image: "/produtos/Kit-Pilhas-Recarregaveis-Carregador.webp",
    rating: 50000,
    store: "Mercado Livre",
    installments: "2x de R$ 25,00",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/15U2YZG",
  },
  {
    title: "Filtro de Linha Intelbras EPE 205 com 5 Tomadas",
    category: "Energia",
    price: "R$ 89,90",
    oldPrice: "R$ 109,90",
    discount: "-18%",
    image: "/produtos/Filtro-Linha-Intelbras-EPE205.webp",
    rating: 850,
    store: "Mercado Livre",
    installments: "3x de R$ 29,97",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1ygNE87",
  },
  {
    title: "Carregador GaN 65W USB-C e USB 3.0",
    category: "Energia",
    price: "R$ 49,90",
    oldPrice: "R$ 69,90",
    discount: "-28%",
    image: "/produtos/Carregador-GaN-65W.webp",
    rating: 30,
    store: "Mercado Livre",
    installments: "2x de R$ 24,95",
    shipping: "Frete grátis",
    affiliate: "https://meli.la/1mbJDPH",
  },
]

async function main() {
  for (const product of products) {
    await prisma.product.upsert({
      where: { affiliate: product.affiliate },
      update: product,
      create: product,
    })
  }

  console.log(`${products.length} produtos sincronizados no PostgreSQL.`)
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
