import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  {
    title: 'Notebook Acer Aspire 5 Intel Core i5 16GB SSD 512GB',
    category: 'Notebooks',
    price: 'R$ 2.999,00',
    oldPrice: 'R$ 3.529,00',
    discount: '-15%',
    image: '/produtos/Notebook-Acer-Aspire-5.jpg',
    rating: 150,
    store: 'Mercado Livre',
    installments: '10x de R$ 299,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1xjmjVS',
  },
  {
    title: 'Impressora multifuncional cor Epson EcoTank L3250',
    category: 'Impressora',
    price: 'R$ 1.221,00',
    oldPrice: 'R$ 1.359,00',
    discount: '-10%',
    image: '/produtos/Impressora-multifuncional-Epson-L3250.jpg',
    rating: 65000,
    store: 'Mercado livre',
    installments: '12x de 10x R$ 118,53',
    shipping: 'Frete Gratis',
    affiliate: 'https://meli.la/286F1hT',
  },
  {
    title: 'Notebook Lenovo IdeaPad 1 Ryzen 5 7520U 8GB SSD 256GB',
    category: 'Notebooks',
    price: 'R$ 2.399,00',
    oldPrice: 'R$ 2.799,00',
    discount: '-14%',
    image: '/produtos/Notebook-Lenovo-IdeaPad-1.webp',
    rating: 420,
    store: 'Mercado Livre',
    installments: '10x de R$ 239,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1SKAReQ',
  },
  {
    title: 'Notebook Dell Inspiron 15 Core i5 16GB SSD 512GB',
    category: 'Notebooks',
    price: 'R$ 3.799,00',
    oldPrice: 'R$ 4.299,00',
    discount: '-12%',
    image: '/produtos/Notebook-Dell-Inspiron-15.webp',
    rating: 286,
    store: 'Mercado Livre',
    installments: '10x de R$ 379,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2Vyvqpc',
  },
  {
    title: 'Monitor Gamer LG UltraGear 24 polegadas IPS 180Hz',
    category: 'Monitores',
    price: 'R$ 899,00',
    oldPrice: 'R$ 1.049,00',
    discount: '-14%',
    image: '/produtos/Monitor-LG-UltraGear-24.webp',
    rating: 534,
    store: 'Mercado Livre',
    installments: '10x de R$ 89,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2gMx1SN',
  },
  {
    title: 'Monitor Samsung T350 24 polegadas Full HD IPS',
    category: 'Monitores',
    price: 'R$ 649,00',
    oldPrice: 'R$ 749,00',
    discount: '-13%',
    image: '/produtos/Monitor-Samsung-T350-24.webp',
    rating: 812,
    store: 'Mercado Livre',
    installments: '10x de R$ 64,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2omqkPs',
  },
  {
    title: 'SSD Kingston NV2 1TB NVMe M.2',
    category: 'Armazenamento',
    price: 'R$ 429,90',
    oldPrice: 'R$ 499,90',
    discount: '-14%',
    image: '/produtos/SSD-Kingston-NV2-1TB.webp',
    rating: 1290,
    store: 'Mercado Livre',
    installments: '10x de R$ 42,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1jbxXEX',
  },
  {
    title: 'SSD Kingston A400 480GB SATA',
    category: 'Armazenamento',
    price: 'R$ 219,90',
    oldPrice: 'R$ 259,90',
    discount: '-15%',
    image: '/produtos/SSD-Kingston-A400-480GB.webp',
    rating: 2380,
    store: 'Mercado Livre',
    installments: '7x de R$ 31,41',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1NheSfj',
  },
  {
    title: 'Memória Kingston Fury Beast 16GB DDR4 3200MHz',
    category: 'Componentes',
    price: 'R$ 279,90',
    oldPrice: 'R$ 329,90',
    discount: '-15%',
    image: '/produtos/Memoria-Kingston-Fury-Beast-16GB.webp',
    rating: 746,
    store: 'Mercado Livre',
    installments: '9x de R$ 31,10',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2Eynffk',
  },
  {
    title: 'Teclado Mecânico Gamer Redragon Kumara K552',
    category: 'Periféricos',
    price: 'R$ 249,90',
    oldPrice: 'R$ 299,90',
    discount: '-17%',
    image: '/produtos/Teclado-Redragon-Kumara-K552.webp',
    rating: 1640,
    store: 'Mercado Livre',
    installments: '8x de R$ 31,24',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2CTAKLL',
  },
  {
    title: 'Mouse Gamer Logitech G203 Lightsync RGB',
    category: 'Periféricos',
    price: 'R$ 129,90',
    oldPrice: 'R$ 159,90',
    discount: '-19%',
    image: '/produtos/Mouse-Logitech-G203.webp',
    rating: 3210,
    store: 'Mercado Livre',
    installments: '4x de R$ 32,48',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2cKanGT',
  },
  {
    title: 'Headset Gamer HyperX Cloud Stinger 2',
    category: 'Periféricos',
    price: 'R$ 299,90',
    oldPrice: 'R$ 349,90',
    discount: '-14%',
    image: '/produtos/Headset-HyperX-Cloud-Stinger-2.webp',
    rating: 688,
    store: 'Mercado Livre',
    installments: '10x de R$ 29,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2FaqZ6E',
  },
  {
    title: 'Webcam Logitech C920 Full HD 1080p',
    category: 'Periféricos',
    price: 'R$ 429,90',
    oldPrice: 'R$ 499,90',
    discount: '-14%',
    image: '/produtos/Webcam-Logitech-C920.webp',
    rating: 925,
    store: 'Mercado Livre',
    installments: '10x de R$ 42,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2KHmnWX',
  },
  {
    title: 'Roteador TP-Link Archer AX12 Wi-Fi 6 Dual Band',
    category: 'Redes',
    price: 'R$ 299,90',
    oldPrice: 'R$ 349,90',
    discount: '-14%',
    image: '/produtos/Roteador-TP-Link-Archer-AX12.webp',
    rating: 472,
    store: 'Mercado Livre',
    installments: '10x de R$ 29,99',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/2c5yGC6',
  },
  {
    title: 'Nobreak Intelbras Attiv 1200VA Bivolt',
    category: 'Energia',
    price: 'R$ 749,00',
    oldPrice: 'R$ 849,00',
    discount: '-12%',
    image: '/produtos/Nobreak-Intelbras-Attiv-1200VA.webp',
    rating: 318,
    store: 'Mercado Livre',
    installments: '10x de R$ 74,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1Wx6JkB',
  },
  {
    title: 'Placa de Vídeo Zotac GeForce RTX 4060 Twin Edge 8GB',
    category: 'Componentes',
    price: 'R$ 2.199,00',
    oldPrice: 'R$ 2.499,00',
    discount: '-12%',
    image: '/produtos/Placa-Video-Zotac-RTX-4060.webp',
    rating: 359,
    store: 'Mercado Livre',
    installments: '10x de R$ 219,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/1VgnfYT',
  },
  {
    title: 'Processador AMD Ryzen 5 5600GT com Radeon Graphics',
    category: 'Componentes',
    price: 'R$ 899,00',
    oldPrice: 'R$ 1.049,00',
    discount: '-14%',
    image: '/produtos/Processador-AMD-Ryzen-5-5600GT.webp',
    rating: 587,
    store: 'Mercado Livre',
    installments: '10x de R$ 89,90',
    shipping: 'Frete grátis',
    affiliate: 'https://meli.la/29PKCVx',
  },
]

async function main() {
  for (const product of products) {
    await prisma.product.upsert({
      where: { affiliate: product.affiliate },
      update: product,
      create: product,
    })
  }

  console.log(`${products.length} produtos sincronizados no PostgreSQL.`)
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
