import { requireAdmin } from '@/lib/require-admin'
import { isAdminMfaEnabled } from '@/lib/admin-auth'
import { ExternalLink, KeyRound, Mail, MapPin, MessageCircle, ShieldCheck } from 'lucide-react'

export default async function AdminSettingsPage() {
  await requireAdmin()
  const mfaEnabled = isAdminMfaEnabled()

  return <div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-brand-400">Sistema</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Configurações</h1><p className="mt-2 text-slate-400">Informações publicadas e atalhos administrativos.</p><section className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-xl font-black">Contato da loja</h2><div className="mt-6 grid gap-4 text-sm"><p className="flex items-center gap-3 rounded-xl bg-black/20 p-4"><Mail className="text-brand-400" size={19} /> devrobertovitalino@gmail.com</p><p className="flex items-center gap-3 rounded-xl bg-black/20 p-4"><MessageCircle className="text-emerald-400" size={19} /> (67) 98479-3793</p><p className="flex items-center gap-3 rounded-xl bg-black/20 p-4"><MapPin className="text-amber-400" size={19} /> Mato Grosso do Sul</p></div></div><div className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-xl font-black">Acessos e segurança</h2><div className="mt-6 grid gap-4"><div className="flex items-start gap-3 rounded-xl bg-emerald-500/10 p-4"><ShieldCheck className="mt-0.5 shrink-0 text-emerald-300" size={20} /><div><strong className="text-sm">Painel protegido</strong><p className="mt-1 text-sm text-slate-400">Todas as páginas administrativas exigem autenticação.</p></div></div><div className={`flex items-start gap-3 rounded-xl p-4 ${mfaEnabled ? 'bg-emerald-500/10' : 'bg-amber-500/10'}`}><KeyRound className={`mt-0.5 shrink-0 ${mfaEnabled ? 'text-emerald-300' : 'text-amber-300'}`} size={20} /><div><strong className="text-sm">Segundo fator {mfaEnabled ? 'ativado' : 'aguardando ativação'}</strong><p className="mt-1 text-sm text-slate-400">{mfaEnabled ? 'O login exige o código do aplicativo autenticador.' : 'Execute npm run mfa:setup e salve a chave no Vercel para ativar.'}</p></div></div><a href="/minha-conta" target="_blank" rel="noopener noreferrer" className="flex items-center justify-between rounded-xl border border-white/10 p-4 text-sm font-bold hover:border-white/20">Área do cliente <ExternalLink size={17} /></a><a href="/" target="_blank" rel="noopener noreferrer" className="flex items-center justify-between rounded-xl border border-white/10 p-4 text-sm font-bold hover:border-white/20">Página da loja <ExternalLink size={17} /></a></div></div></section></div>
}
